spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  jms:
    pub-sub-domain: false # queue
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.1.106:61616
    pool:
      enabled: true
      max-connections: 5